# Generated by Django 5.2.17 on 2026-10-06 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1–2 Years'), ('3-5', '3–5 Years'), ('5+', '5+ Years')], max_length=20)),
                ('tech_stack', models.JSONField(default=list)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('current_question', models.PositiveIntegerField(default=1)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('completeness_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='WarningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('warning_type', models.CharField(choices=[('lip_movement', 'Lip Movement'), ('eye_movement', 'Eye Movement'), ('smart_device', 'Smart Device')], max_length=30)),
                ('timestamp_seconds', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='interviews.interview')),
            ],
        ),
    ]
