# Generated by Django 5.2.17 on 2026-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warningevent',
            name='screenshot_url',
        ),
        migrations.AddField(
            model_name='warningevent',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='warning_screenshots/'),
        ),
    ]
