# Generated by Django 5.2.17 on 2026-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_warningevent_screenshot_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='interview_recordings/'),
        ),
    ]
