# Generated by Django 5.2.17 on 2026-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
