# Generated by Django 5.2.17 on 2026-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningevent',
            name='warning_type',
            field=models.CharField(choices=[('lip_movement', 'Lip Movement'), ('eye_movement', 'Eye Movement'), ('smart_device', 'Smart Device'), ('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exited')], max_length=30),
        ),
    ]
